### ISSUE TITLE
Improve visibility

### ISSUE THREAD

**Issue by fzaninotto** [sidferreira/aor-firebase-client#1]
Hi! Great lib.

I advise you to add the `admin-on-rest` tag to your Github repository, and open a PR on https://github.com/marmelab/admin-on-rest/blob/master/docs/RestClients.md to add your client there.

**Comment by SidFerreira** [comment]
Sorry my lack of knowledge, but how do I add the `admin-on-rest` tag?

**Comment by SidFerreira** [comment]
I've added a label, not sure if that's what you meant

**Comment by fzaninotto** [comment]
In GitHub lingo, what I meant is called "topics", and you can customize them from your repository home page:

![image](https://user-images.githubusercontent.com/99944/27556616-96ec116c-5ab6-11e7-88ee-c779cddda269.png)

**Comment by sidferreira** [comment]
Thanks @fzaninotto !
