### ISSUE TITLE
Example Firebase schema?

### ISSUE THREAD

**Issue by JCDJulian** [sidferreira/aor-firebase-client#24]
Hi, starting up a new project with this client. I was wondering if there were a way to access the Firebase schema in the demo, or at least for you to provide an example. No problem getting the auth to work, but having issues loading resources as the loading circle just keeps spinning without any feedback on whether it's actually sending the firebase db query.

**Comment by JCDJulian** [comment]
To get more specific, I have a schema like this:

```
app-name
    surveys
        link: "test.com"
        name: "s1"
```

I've listed surveys as a tracked resource.

const trackedResources = ['surveys']

```
const App = () => (
    <Admin restClient={RestClient(trackedResources, firebaseConfig)} >
        <Resource name="surveys" list={SurveyList} />
    </Admin>
);
```

The surveys aren't loading, but I am pulling the data from Firebase and getting an exception:

`TypeError: can't assign to properties of (new String("test.com")): not an object`

**Comment by JCDJulian** [comment]
Never mind, figured it out. Sorry, new to firebase.

Updated schema that worked:
```

groundworkv0
    surveys
        s1
           link: test.com
           name: s1 
```

**Comment by sidferreira** [comment]
@JCDJulian No worries! Welcome!
