### ISSUE TITLE
Firestore storage

### ISSUE THREAD

**Issue by shrizalz** [sidferreira/aor-firebase-client#25]
Is any way this can be used to connect with firestore instead of realtime database?

**Comment by sidferreira** [comment]
Will work on that mid november or december.

Em 20 de out de 2017 4:09 AM, "Shahrizal Zoljefry" <notifications@github.com>
escreveu:

**Comment by shrizalz** [comment]
Thanks, Looking forward :)

**Comment by priezz** [comment]
@sidferreira, hi there! I have implemented Firestore client, base on your `upload` branch. However, this is done for my own needs and I currently have no time for documentation. Do you want me to share the code?

P.S. My implementation has differen upload function (with customizable saving paths, no dimensions savings) and support for firestore subcollections to use them transparently with AOR.

**Comment by sidferreira** [comment]
Yes! Something is better than nothing!!!

**Comment by priezz** [comment]
Here is the [gist](https://gist.github.com/priezz/40ba68ab0ddcdb0bdb73972fea5c0067).

**Comment by priezz** [comment]
@sidferreira, I have a lot of updates (page content reactivity, better schema configuration, ...) since gist publication and going to have more. So, when you are ready to look at the code, please write here, I will update the gist.
