### ISSUE TITLE
What the hell Sid?!?!?!

### ISSUE THREAD

**Issue by sidferreira** [sidferreira/aor-firebase-client#41]
So, guys, I'm really sad that I'm not delivering the updates here as I want.
The fact is that I'm having a CRAZY amount of work since August.

So, in order to plan things a bit, I would like to know if you guys would like to help me on TESTING the new version.
Testing is BY FAR what takes most of the time. If you guys are up to helping on it, I can start working in a new version (react-admin based and include Firestore) if you guys accept to help me on it.

So, I would like to anyone who wants to help at least on testing to reply here.

@Kmaschta @photocat @nietzscheson @afilp @pelanmar1 @leomyth330 @erickvictor @georgerb @bvivek20  @jesster2k10 @matseriksen @roadev @jjjjjjjjjjjjjjjjjjjj @RWOverdijk @Hosnidokht

Important to mention that I'm not using it that much, so, I will need this help in order to help you.
I want to rewrite it from scratch, first for RealTime Database and later for Firestore, in a well structured way that allows you to override parts of the code and improve functionality.

ps: Anyone that wants helps CODING it will be welcome too :)

**Comment by Kmaschta** [comment]
Hi Sid!

Maintaining OSS projects is hard, and the burden can be very stressful.
Please, don't receive the issue #40 as an act of impatience, I just opened it in my way to update the React Admin doc. Some users were complaining that data providers listed here was out of date.

Since `aor-firebase-client` doesn't support the new RA version yet, we didn't delete it from the doc but we moved it into a new paragraph [Legacy Data Providers](https://marmelab.com/react-admin/DataProviders.html#legacy-data-providers) so that the newcomers know that an effort to support their favorite provider is available but waiting for a helping hand.

I'm not a Firebase user, so I can't really help you to test it. But if you have any issue, question or any doubt about the React Admin API or usage, don't hesitate to ping me!
It would be a pleasure to help you with this new version.

**Comment by nietzscheson** [comment]
Hi @sidferreira. In fact, I was starting an alternate project since I did not see recent updates and the pulls were not answered: https://github.com/nietzscheson/ra-firebase-client

I would like to collaborate ... I see that many of us need this client to be updated.

I will be pending. Greetings.

**Comment by sidferreira** [comment]
@Kmaschta It was actually a self-critic :)

@nietzscheson What's your current status on it? What's your timezone??

**Comment by nietzscheson** [comment]
Hey, @sidferreira my timezone is: (GMT-5) I from Cancun, Mexico.

The client has barely been created... but, I think it would be better to do everything in this... I could support you. Although I'm not an expert in Redux, I'm thinking of using it...

**Comment by sidferreira** [comment]
@nietzscheson We don't need to use redux deeply

**Comment by nietzscheson** [comment]
@sidferreira I repeat... I offer my support to try to update this package...

**Comment by sidferreira** [comment]
Ok, this week is my kids' birthday, but monday I'll start on it.
Let's first fix the current one to the most up-to-date verson and then we work with React Admin

**Comment by sidferreira** [comment]
@nietzscheson @Kmaschta branch for v0.4.0 created/updated. 

I did some breaking changes at this moment, but we can revert if you guys think it's useful. 

I didn't worked on the auth yet

**Comment by afilp** [comment]
@sidferreira Thanks, will you rename the package to `ra-firebase-client` and then release in npm?

**Comment by sidferreira** [comment]
@afilp I'm not sure as there's another one already: https://github.com/nietzscheson/ra-firebase-client

**Comment by afilp** [comment]
Ok, I understand, even with the old name, is it now `react-admin` ready? Because I see this in `package.json`:

```
  "dependencies": {
    "admin-on-rest": "1",
```

Thank you a lot!

**Comment by sidferreira** [comment]
@afilp I believe it will be compatible, but had no time to do all the tests

**Comment by nietzscheson** [comment]
@afilp the React-Admin people has recomended this data provider: https://marmelab.com/react-admin/DataProviders.html >>> https://github.com/aymendhaya/ra-data-firebase-client

**Comment by Kmaschta** [comment]
We didn't tested it tho. (https://github.com/marmelab/react-admin/pull/2334)

From the README:
> A Firebase Client for the awesome [react-admin](https://github.com/marmelab/react-admin) framework. A continuity for [sidferreira/aor-firebase-client](https://github.com/sidferreira/aor-firebase-client)

It seems like someone was impatient. But it's thrilling to see the community participating!

I suggest that you join your efforts into a single repo.
