### ISSUE TITLE
Data are created but not with the correct path on firebase

### ISSUE THREAD

**Issue by Mcdostone** [sidferreira/aor-firebase-client#7]
Hi guys !

First of all, thanks for your library :) I have a issue when I want to insert data in firebase ! Data are inserted but not in the correct path on firebase !

This is my route when I want to create an event for example: 
`http://localhost:3000/admin/events/create`

![sans titre](https://user-images.githubusercontent.com/6984659/28227230-4778994e-68d9-11e7-994d-83293d32b9be.png)

I would to like that data are inserted into /events, but here data are saved in /admin/events. 
This is normal because your library uses the basepath which corresponds to the location path:
[restClient.js#L142](https://github.com/sidferreira/aor-firebase-client/blob/master/src/restClient.js#L142)

Maybe, it could be better to to get the firebase reference on the resource, not on the basepath, like you do 

Thanks in advance !

**Comment by sidferreira** [comment]
Indeed!!! Fixing!

**Comment by Mcdostone** [comment]
Cool 👍 You have probably the same fix to apply for UPDATE and DELETE !

Thanks for you reactivity !

**Comment by sidferreira** [comment]
@Mcdostone I wasn't expecting people use this fast TBH.
Just published 0.0.8.
