### ISSUE TITLE
Fetch Data from database on demand

### ISSUE THREAD

**Issue by Hosnidokht** [sidferreira/aor-firebase-client#9]
Now, all data is fetched to the client and then all operations like filtering apply to these data in the client side. This approach is not ideal for huge data.

**Comment by sidferreira** [comment]
@Hosnidokht Yes, this is a known issue. But at the same time it's kinda complex have a good silver bullet on that.
If you have suggestions on how to implement it, be welcome to suggest!

**Comment by sidferreira** [comment]
@grahamlyus @Hosnidokht I think we should have a `delegate` property, so the user can override some of the behaviors. We won't be able to make a silver bullet in this case.

**Comment by grahamlyus** [comment]
@sidferreira @Hosnidokht 

I imagine it could get quite tricky to handle this internally in an elegant manner. 

I'm not a firebase expert, but filtering/searching is not it's strong point (especially text) and the best way to do it tends to be very dependent on each individual database. 

I don't have scaling issues as I don't have huge data yet (I'm only using firebase in small side projects, not my day job). Before I found this project I was using js-data and it's firebase plugin, but that also filters, sorts, and paginates everything client side. I hope firebase addresses this before I have this problem ;)

Maybe some kind of "ref decorator callback" property could work that would receive the `ref` that would allow the client to call `equalTo`, etc. before returning. I think it would have to receive the aor `filter`, `pagination`, and `sort` params to be useful and would be reloading data upon each `params` change in `GET_LIST`, `GET_MANY`, `GET_MANY_REFERENCE`.

**Comment by eyalabadi98** [comment]
This is something i'd definitely love to see. I would love to try and help you tackle this problem! this would definitely add a lot of functionality to this package!

**Comment by sidferreira** [comment]
AFAIK it is a Firebase limitation.

**Comment by dobryanskyy** [comment]
so, do I get it correctly - this is a "won't fix"? Because for bigger collections(like log items, etc) - downloading entire collection is really not an option.

**Comment by sidferreira** [comment]
@dobryanskyy yup
Maybe you can use REST instead

**Comment by dobryanskyy** [comment]
I see, thanks
